title: "Sakil Ahmed's Book Tracker Blog"
description: "A curated collection of book reviews and reflections on my literary journey."
theme: minima  # Consider exploring premium themes for a unique look

social_links:
  github: https://github.com/Sakil-Ahmed  # Link to your GitHub profile
  linkedin: https://www.linkedin.com/in/sakil-ahmed-289523198/  # LinkedIn profile link
  

# SEO Enhancements
seo:
  title: "Book Reviews and Reflections | Sakil Ahmed's Blog"
  description: "Explore thoughtful book reviews and insights from Sakil Ahmed, covering a range of genres from fiction to technology."
  keywords:
    - "book reviews"
    - "Sakil Ahmed"
    - "literary blog"
    - "reading journey"
    - "thoughtful insights"
  author: "Sakil Ahmed"

# Blog Enhancements
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives  # Organize posts into monthly/annual archives
  - jekyll-related-posts  # Display related posts for better user engagement

# Theme Customization
minima:
  skin: dark  # You can change this to 'light', 'solarized' for different aesthetics
  social_links_display: true  # Enable social icons in the header/footer
  accent_color: "#ff5733"  # Choose a custom color to highlight specific elements
  fonts:  # Customized fonts for a personalized look
  body: "'Open Sans', sans-serif"
  headers: "'Lora', serif"

# Navigation Enhancements
navigation:
  - title: "Home"
    url: /
  - title: "Book Reviews"
    url: /book-reviews/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
